name: LUIS-DevOps-Setup

# Trigger the workflow on tag
on:
  push:
    # matched against tags
    tags:   
      - setup     
      - setup* 

env:
  # Set the Azure Resource Group name
  RESOURCE_GROUP_NAME: luisDevOpsRG
  # Set the Azure Resource Group location
  RESOURCE_GROUP_REGION: westus
  # Set the name of the master LUIS app
  LUIS_APP_NAME: LUISDevOps-master

jobs:
  build:
    name: Setup Azure resources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '1'

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI create Resource Group, LUIS resources and Storage account
      uses: azure/CLI@v1
      with:
        azcliversion: 2.2.0
        inlineScript: az deployment create -l westus --template-file setup/azuredeploy.json --parameters @setup/azuredeployparameters.json

    - name: Get Resource attributes
      run: |
          azureLuisResourceName=$(node -pe 'JSON.parse(process.argv[1]).parameters["LUIS_Prediction_Resource_name"].value' "$(cat setup/azuredeployparameters.json)")
          echo "::set-env name=AzureLuisResourceName::$azureLuisResourceName"
          azureLuisAuthoringResourceName=$(node -pe 'JSON.parse(process.argv[1]).parameters["LUIS_Authoring_Resource_name"].value' "$(cat setup/azuredeployparameters.json)")
          echo "::set-env name=AzureLuisAuthoringResourceName::$azureLuisAuthoringResourceName"
          azureLuisRegion=$(node -pe 'JSON.parse(process.argv[1]).parameters["Azure_region"].value' "$(cat setup/azuredeployparameters.json)")

    - name: Get LUIS authoring key
      run: |
          az cognitiveservices account keys list --name $AzureLuisAuthoringResourceName --resource-group $RESOURCE_GROUP_NAME > authoring.json
          authoringKey=$(node -pe 'JSON.parse(process.argv[1]).key1' "$(cat authoring.json)")
          echo "::set-env name=luisAuthoringKey::$authoringKey"

    - name: Install @microsoft/botframework-cli
      run:  npm i -g @microsoft/botframework-cli
        
    # Telemetry prompt botcli  bug - https://github.com/microsoft/botframework-cli/issues/370
    - name: Disable botframework-cli telemetry
      run: 'mkdir -p ~/.config/@microsoft/botframework-cli; echo "{ \"telemetry\": false }" > $_/config.json'

    - name: Create LUIS application
      run: |
        bf luis:application:create --name $LUIS_APP_NAME --subscriptionKey $luisAuthoringKey --endpoint $luisEndpoint --versionId=0.1
        bf luis:application:list --subscriptionKey $luisAuthoringKey --endpoint $luisEndpoint --out appList.json
        luisAppId=`cat appList.json |  jq -c '.[] | select(.name | . and contains('\"$LUIS_APP_NAME\"')) | .id'`
        luisAppId=$(echo $luisAppId | xargs)
        echo "Found LUIS app: $luisAppId"
        echo "::set-env name=luisAppId::$luisAppId" 
      env:
        luisEndpoint: https://${{ env.azureLuisRegion }}.api.cognitive.microsoft.com